### ISSUE TITLE
level:Tree, tree, tree again

### ISSUE THREAD

**Issue by GamingInky** [andybalaam/rabbit-escape#113]
```
:name=Tree, tree, tree again
:description=You have to save all.
:hint1=Use all the bridges.
:hint2=Explode is not needed.
:hint3=The lowest branch is not needed.
:author_name=colonelfazackerley
:author_url=https://github.com/colonelfazackerley
:num_rabbits=4
:num_to_save=4
:rabbit_delay=15
:bash=3
:bridge=5
:dig=2
:block=1
:explode=1
:music=tryad-empty
#                               
            O  /#               
            #####               
              ##                
              ##                
              ##########\       
      #       ###      ##       
     /#####\  ###               
     #    #######               
             ####               
 Q           ####              #
\           /####\           ###
############################### 
```

I think maybe this could go in the Deja Vu level set

**Comment by andybalaam** [comment]
Cool. I'll try to solve this when I get time. How do people feel about slightly modified levels in Deja Vue? I'm a bit against it if we can avoid it. But maybe someone can make this solution possible in the exact same level as the original? If not maybe we could use this in another set?

**Comment by tttppp** [comment]
I think there's probably enough potential for non-modified levels to make a Deja Vu set. However I like the idea of a set of slightly modified levels - a "twisted" set, or "alternate universe", or something.

I keep reading the hints for @GamingInky's sets by accident :(  I'll try to forget what I read before I try this.

**Comment by tttppp** [comment]
Totally impossible??  I just had a quick go, but couldn't work out how to get close.  There were a lot of spaces missing from the bottom line - maybe the level is malformed?

**Comment by andybalaam** [comment]
Yes I think the bottom line is missing.

**Comment by GamingInky** [comment]
Fixed it.

**Comment by GamingInky** [comment]
I think we should say that a level's lines can be different lenth and the longest line is the edge of the level because I'm having some touble write level then submiting them to github.

**Comment by andybalaam** [comment]
Hmm. In general I am in favour of very strict checking but maybe we could have a preprocessor that takes in human-edited levels and makes them acceptable.

**Comment by tttppp** [comment]
I still think this is impossible :-)  Maybe I'm missing something though.  Here's an easy version that I just solved:

```
:name=Tree, tree, tree again (Easy)
:description=You have to save all.
:author_name=tttppp
:author_url=https://github.com/tttppp
:num_rabbits=4
:num_to_save=4
:rabbit_delay=15
:bash=20
:bridge=20
:dig=20
:block=20
:explode=20
:music=tryad-empty
#                               
            O  /#               
            #####               
              ##                
              ##                
              ##########\       
      #       ###      ##       
     /#####\  ###               
     #    #######               
             ####               
 Q           ####              #
#           /####\           ###
#################               
```

**Comment by andybalaam** [comment]
I think it's still broken - I think there needs to be a bottom line which is mostly #s.  I'll prod @GamingInky to check it properly this time.

**Comment by GamingInky** [comment]
it's not my fault, when I update the comment it gets rid of those #'s

**Comment by andybalaam** [comment]
I have now tested it, and it's working.  Slightly tricky, and fun.

**Comment by andybalaam** [comment]
When I say working I also mean soluble btw.

**Comment by GamingInky** [comment]
year I fixed it!

**Comment by andybalaam** [comment]
This is released in deja vu
